// Preset brand styles so visitors (including signed-out users) can preview
// the welcome email experience without running an extraction. The payload
// mirrors the brand_style object returned by the Dreamlit extraction API;
// each was generated by running the real extraction against the brand's site.

export type BrandStylePreset = {
  id: string;
  label: string;
  websiteUrl: string;
  brandStyle: Record<string, unknown>;
};

export const BRAND_STYLE_PRESETS: BrandStylePreset[] = [
  // Vercel preset kept for reference; not currently offered.
  /*
  {
    id: "vercel",
    label: "Vercel",
    websiteUrl: "https://vercel.com",
    brandStyle: {
      "name": "Vercel",
      "brandName": "Vercel",
      "website": "vercel.com",
      "colorScheme": "light",
      "backgroundColor": "#FAFAFA",
      "foregroundColor": "#171717",
      "accentColor": "#171717",
      "headingFontFamily": "Geist",
      "bodyFontFamily": "Geist",
      "buttonBackgroundColor": "#171717",
      "buttonTextColor": "#FFFFFF",
      "buttonBorderColor": null,
      "buttonBorderRadiusPx": 100,
      "brandSubtext": "Build and deploy on the AI Cloud.",
      "footerAddress": null,
      "logoCdnUrl": "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/logo/019eae6e-4990-718f-9849-05a6689d90da",
      "logoWidth": 240,
      "logoHeight": 48,
      "firecrawlSourceUrl": "https://vercel.com/",
      "firecrawlPulledAt": "2026-06-09T22:08:44.718Z",
      "firecrawlBrandName": "Vercel",
      "firecrawlHomepageSummary": "Vercel provides developer tools and cloud infrastructure to build, scale, and secure a faster, personalized web.",
      "firecrawlAudience": "Developers, teams deploying applications, and businesses looking for optimized web solutions.",
      "firecrawlToneWords": [
        "innovative",
        "fast",
        "secure",
        "scalable",
        "developer-friendly"
      ],
      "firecrawlBusinessType": "SaaS",
      "firecrawlBusinessModel": "Subscription-based software services for developers and businesses.",
      "firecrawlPricingDetails": [
        "No public pricing found"
      ],
      "firecrawlRecommendedEmailWorkflows": [
        "onboarding",
        "trial activation",
        "abandoned cart recovery",
        "winback",
        "product recommendation"
      ],
      "firecrawlHeroHeadline": "Build and deploy on the AI Cloud.",
      "firecrawlHeroSubheadline": "Vercel provides tools to build, scale, and secure a personalized web experience.",
      "firecrawlPrimaryCtaText": "Start Deploying",
      "firecrawlSecondaryCtaText": "Get a Demo",
      "firecrawlValueProps": [
        "Faster build times with optimized infrastructure",
        "Seamless deployment from git",
        "Secure, scalable cloud solutions",
        "AI-driven application enhancements",
        "Efficient, user-friendly developer tools"
      ],
      "firecrawlWelcomeEmailCopy": {
        "subject": "Welcome to Vercel!",
        "preheader": "Your journey with powerful tools starts now.",
        "headline": "Welcome to the Vercel Community!",
        "bodyParagraphs": [
          "We're excited to have you on board! Vercel provides the tools you need to create, build, and deploy your applications seamlessly.",
          "Get started by exploring our comprehensive documentation or jump right in with our templates. Join our vibrant community and enhance your building experience!",
          "Thank you for choosing Vercel, we can't wait to see what you'll create!"
        ]
      },
      "firecrawlHeadingFontFamily": "Geist",
      "firecrawlHeadingFallbackFontFamily": "Helvetica",
      "firecrawlBodyFontFamily": "Geist",
      "firecrawlBodyFallbackFontFamily": "Helvetica",
      "firecrawlPrimaryColor": "#171717",
      "firecrawlSecondaryColor": "#FF0000",
      "firecrawlAccentColor": "#171717",
      "firecrawlBackgroundColor": "#FAFAFA",
      "firecrawlTextColor": "#171717",
      "firecrawlLinkColor": "#0072F5",
      "firecrawlThemePreference": "light",
      "firecrawlCtaBackgroundColor": "#171717",
      "firecrawlCtaTextColor": "#FFFFFF",
      "firecrawlCtaBorderColor": "",
      "firecrawlCtaBorderRadius": "100px",
      "firecrawlScreenshotCdnUrl": "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/screenshot/019eae6e-4a82-70e6-9bbb-444bc2f7b93e",
      "socialLinks": [
        {
          "label": "Website",
          "url": "https://vercel.com/"
        },
        {
          "label": "X",
          "url": "https://x.com/vercel"
        },
        {
          "label": "YouTube",
          "url": "https://youtube.com/@VercelHQ"
        },
        {
          "label": "LinkedIn",
          "url": "https://linkedin.com/company/vercel"
        }
      ],
      "firecrawlColors": [
        {
          "firecrawlColor": "#B055EA",
          "firecrawlRole": "Primary",
          "firecrawlComponent": "Brand palette",
          "firecrawlUsage": "Main CTA, active state, or strongest brand mark."
        },
        {
          "firecrawlColor": "#FF0000",
          "firecrawlRole": "Secondary",
          "firecrawlComponent": "Brand palette",
          "firecrawlUsage": "Supporting actions, surfaces, or contrast color."
        },
        {
          "firecrawlColor": "#171717",
          "firecrawlRole": "Accent",
          "firecrawlComponent": "Brand palette",
          "firecrawlUsage": "Small highlight, badge, or emphasis color."
        },
        {
          "firecrawlColor": "#FAFAFA",
          "firecrawlRole": "Background",
          "firecrawlComponent": "Page background",
          "firecrawlUsage": "Dominant page or content surface."
        },
        {
          "firecrawlColor": "#171717",
          "firecrawlRole": "Text",
          "firecrawlComponent": "Text",
          "firecrawlUsage": "Default body text on the main surface."
        },
        {
          "firecrawlColor": "#0072F5",
          "firecrawlRole": "Link",
          "firecrawlComponent": "Links",
          "firecrawlUsage": "Standalone text links, not button labels."
        },
        {
          "firecrawlColor": "#000000",
          "firecrawlRole": "background",
          "firecrawlComponent": "main",
          "firecrawlUsage": "background color for main areas"
        },
        {
          "firecrawlColor": "#FFFFFF",
          "firecrawlRole": "text",
          "firecrawlComponent": "main",
          "firecrawlUsage": "primary text color"
        }
      ],
      "firecrawlImages": [
        {
          "firecrawlImageUrl": "https://assets.vercel.com/image/upload/q_auto/front/favicon/vercel/favicon.ico",
          "firecrawlAltText": null,
          "firecrawlRole": "Favicon",
          "cdnUrl": "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019eae6e-4a88-71cb-a512-17671b4b8054",
          "mimeType": "image/x-icon",
          "width": 48,
          "height": 48
        },
        {
          "firecrawlImageUrl": "https://assets.vercel.com/image/upload/contentful/image/e5382hct74si/4JmubmYDJnFtstwHbaZPev/0c3576832aae5b1a4d98c8c9f98863c3/Vercel_Home_OG.png",
          "firecrawlAltText": null,
          "firecrawlRole": "OG Image",
          "cdnUrl": "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019eae6e-4ab5-7461-8327-c997db7c7fc9",
          "mimeType": "image/png",
          "width": 1200,
          "height": 628
        },
        {
          "firecrawlImageUrl": "https://vercel.com/vc-ap-vercel-marketing/_next/static/immutable/media/vercel-light.23p4dw77xj4pk.svg",
          "firecrawlAltText": "Vercel logo",
          "firecrawlRole": "logo",
          "cdnUrl": "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019eae6e-4b53-72db-b86f-b16e57a9abb2",
          "mimeType": "image/png",
          "width": 307,
          "height": 267
        },
        {
          "firecrawlImageUrl": "https://vercel.com/vc-ap-vercel-marketing/_next/static/immutable/media/vercel-dark.05qiau0oi3y6n.svg",
          "firecrawlAltText": "Vercel logo dark mode",
          "firecrawlRole": "logo",
          "cdnUrl": "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019eae6e-4bf0-7778-a455-b5311e5aa921",
          "mimeType": "image/png",
          "width": 307,
          "height": 267
        },
        {
          "firecrawlImageUrl": "https://vercel.com/vc-ap-vercel-marketing/_next/static/immutable/media/adobe-dark.2yxcg9r5ex73q.svg",
          "firecrawlAltText": null,
          "firecrawlRole": null,
          "cdnUrl": "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019eae6e-4ad4-744e-b0c0-af1a5c660668",
          "mimeType": "image/png",
          "width": 747,
          "height": 197
        },
        {
          "firecrawlImageUrl": "https://vercel.com/vc-ap-vercel-marketing/_next/static/immutable/media/chicos-dark.2k18-v2l9fsvr.svg",
          "firecrawlAltText": null,
          "firecrawlRole": null,
          "cdnUrl": "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019eae6e-4ad2-726d-b56f-3fa5c6229e39",
          "mimeType": "image/png",
          "width": 747,
          "height": 155
        }
      ]
    },
  },
  */
  {
    id: "happyboards",
    label: "HappyBoards",
    websiteUrl: "https://happyboards.com",
    brandStyle: {
      name: "HappyBoards",
      brandName: "HappyBoards",
      website: "happyboards.com",
      colorScheme: "light",
      backgroundColor: "#FAF8FB",
      foregroundColor: "#6B5D57",
      accentColor: "#7851A9",
      headingFontFamily: "Playfair Display",
      bodyFontFamily: "Rubik",
      buttonBackgroundColor: "#7851A9",
      buttonTextColor: "#FFFFFF",
      buttonBorderColor: null,
      buttonBorderRadiusPx: 999,
      brandSubtext: "Chef-crafted charcuterie boards, made fresh daily with same-day delivery.",
      footerAddress: null,
      logoCdnUrl:
        "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/logo/019ead46-7115-760d-8a6f-9a819a79eeb8",
      logoWidth: 256,
      logoHeight: 256,
      firecrawlSourceUrl: "https://happyboards.com/",
      firecrawlPulledAt: "2026-06-09T16:45:38.625Z",
      firecrawlBrandName: "HappyBoards",
      firecrawlHomepageSummary:
        "HappyBoards sells chef-crafted charcuterie boards, offering same-day delivery in over 54 cities. The brand emphasizes fresh ingredients and customizable options for various occasions including corporate events and private gatherings.",
      firecrawlAudience:
        "Individuals and companies looking for gourmet catering solutions, event planners, and anyone celebrating special occasions.",
      firecrawlToneWords: ["friendly", "delightful", "inviting", "sophisticated", "cheerful"],
      firecrawlBusinessType: "ecommerce",
      firecrawlBusinessModel: "direct-to-consumer",
      firecrawlPricingDetails: [
        "Assorted Pastry Tray: $70",
        "Alpine Style Cheeses - Gruyere: $24",
        "Alpine Style Cheeses - Challerhocker: $22",
        "Art of Charcuterie Tasting Board: $398.75",
        "3-4 Person Breakfast Box: $0",
        "No public pricing found for additional items.",
      ],
      firecrawlRecommendedEmailWorkflows: [
        "abandoned cart recovery",
        "onboarding",
        "winback",
        "replenishment reminder",
        "trial activation",
      ],
      firecrawlHeroHeadline: "Every Board Has A Story",
      firecrawlHeroSubheadline: "Chef-crafted charcuterie boards, made fresh this morning.",
      firecrawlPrimaryCtaText: "Start Order",
      firecrawlSecondaryCtaText: "Explore Occasions",
      firecrawlValueProps: [
        "Made fresh daily",
        "Same-day delivery",
        "Never frozen",
        "Wide selection for every occasion",
        "HappyRewards loyalty program offers 8% back",
      ],
      firecrawlWelcomeEmailCopy: {
        subject: "Welcome to HappyBoards!",
        preheader: "Experience gourmet charcuterie delivered to your door.",
        headline: "Thank you for joining HappyBoards!",
        bodyParagraphs: [
          "At HappyBoards, every board has a story. We pride ourselves on crafting charcuterie boards that are made fresh daily, perfect for every occasion.",
          "Explore our chef-curated selection and enjoy same-day delivery right to your door. With HappyRewards, you'll receive perks and points with every order. We're excited to serve you!",
        ],
      },
      firecrawlHeadingFontFamily: "Playfair Display",
      firecrawlHeadingFallbackFontFamily: "Georgia",
      firecrawlBodyFontFamily: "Rubik",
      firecrawlBodyFallbackFontFamily: "Helvetica",
      firecrawlPrimaryColor: "#7851A9",
      firecrawlSecondaryColor: "#101828",
      firecrawlAccentColor: "#7851A9",
      firecrawlBackgroundColor: "#FAF8FB",
      firecrawlTextColor: "#6B5D57",
      firecrawlLinkColor: "#7851A9",
      firecrawlThemePreference: "light",
      firecrawlCtaBackgroundColor: "#7851A9",
      firecrawlCtaTextColor: "#FFFFFF",
      firecrawlCtaBorderColor: "",
      firecrawlCtaBorderRadius: "999px",
      firecrawlScreenshotCdnUrl:
        "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/screenshot/019ead46-71f6-718e-a3d9-f70703b30d1a",
      socialLinks: [
        {
          label: "Website",
          url: "https://happyboards.com/",
        },
        {
          label: "Instagram",
          url: "https://www.instagram.com/tryhappyboards",
        },
        {
          label: "TikTok",
          url: "https://www.tiktok.com/@happyboards",
        },
        {
          label: "LinkedIn",
          url: "https://www.linkedin.com/company/happyboards/",
        },
        {
          label: "YouTube",
          url: "https://www.youtube.com/@HappyBoards",
        },
        {
          label: "Facebook",
          url: "https://www.facebook.com/tryhappyboards",
        },
      ],
      firecrawlColors: [
        {
          firecrawlColor: "#6B5D57",
          firecrawlRole: "Primary",
          firecrawlComponent: "Brand palette",
          firecrawlUsage: "Main CTA, active state, or strongest brand mark.",
        },
        {
          firecrawlColor: "#101828",
          firecrawlRole: "Secondary",
          firecrawlComponent: "Brand palette",
          firecrawlUsage: "Supporting actions, surfaces, or contrast color.",
        },
        {
          firecrawlColor: "#7851A9",
          firecrawlRole: "Accent",
          firecrawlComponent: "Brand palette",
          firecrawlUsage: "Small highlight, badge, or emphasis color.",
        },
        {
          firecrawlColor: "#FAF8FB",
          firecrawlRole: "Background",
          firecrawlComponent: "Page background",
          firecrawlUsage: "Dominant page or content surface.",
        },
        {
          firecrawlColor: "#7851A9",
          firecrawlRole: "Text",
          firecrawlComponent: "Text",
          firecrawlUsage: "Default body text on the main surface.",
        },
        {
          firecrawlColor: "#7851A9",
          firecrawlRole: "Link",
          firecrawlComponent: "Links",
          firecrawlUsage: "Standalone text links, not button labels.",
        },
        {
          firecrawlColor: "#FFFFFF",
          firecrawlRole: "background",
          firecrawlComponent: "page",
          firecrawlUsage: "Subtle background color",
        },
        {
          firecrawlColor: "#F8F8F8",
          firecrawlRole: "section background",
          firecrawlComponent: "sections",
          firecrawlUsage: "Section background",
        },
      ],
      firecrawlImages: [
        {
          firecrawlImageUrl: "https://www.happyboards.com/favicon.ico?favicon.11l0~y~2srv~7.ico",
          firecrawlAltText: null,
          firecrawlRole: "Favicon",
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019ead46-7112-74ee-975a-c42578f8cd1c",
          mimeType: "image/x-icon",
          width: 256,
          height: 256,
        },
        {
          firecrawlImageUrl: "https://www.happyboards.com/logo.png",
          firecrawlAltText: null,
          firecrawlRole: "OG Image",
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019ead46-7105-72a9-826c-e8ef99258bce",
          mimeType: "image/png",
          width: 3081,
          height: 2051,
        },
        {
          firecrawlImageUrl:
            "https://www.happyboards.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo.0_7rtz8d9-ole.png&w=256&q=75",
          firecrawlAltText: "HappyBoards Logo",
          firecrawlRole: "logo",
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019ead46-7089-7674-9a53-dd280843bda1",
          mimeType: "image/png",
          width: 256,
          height: 170,
        },
        {
          firecrawlImageUrl:
            "https://www.happyboards.com/_next/image?url=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1541529086526-db283c563270%3Fw%3D1200%26q%3D80&w=3840&q=75",
          firecrawlAltText: "Classic Charcuterie HappyBoard",
          firecrawlRole: "hero",
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019ead46-70f1-72fb-a6de-e8621ef317e4",
          mimeType: "image/jpeg",
          width: 1200,
          height: 800,
        },
        {
          firecrawlImageUrl:
            "https://www.happyboards.com/_next/image?url=https%3A%2F%2Fhappyoms-production.s3.us-east-2.amazonaws.com%2Fmenu-media%2Fcmmtd6fsc08oq0dqxwmvikkn7%2Fsections%2Fcmmupkbu8009d0do4qu1r83mo%2Fitems%2Fcmmv1p7ug01n90dlg8jy7rp73%2Fimages%2F1773859024961-1.webp%3FX-Amz-Algorithm%3DAWS4-HMAC-SHA256%26X-Amz-Content-Sha256%3DUNSIGNED-PAYLOAD%26X-Amz-Credential%3DAKIAUOMPNW3C6QZBNHSI%252F20260609%252Fus-east-2%252Fs3%252Faws4_request%26X-Amz-Date%3D20260609T164455Z%26X-Amz-Expires%3D3600%26X-Amz-Signature%3Dd2a0f03ce9ccd71dcbc8f5a462d0118af82bd9903c2a947b722fcac300f16895%26X-Amz-SignedHeaders%3Dhost%26x-amz-checksum-mode%3DENABLED%26x-id%3DGetObject&w=3840&q=75",
          firecrawlAltText: null,
          firecrawlRole: null,
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019ead46-729a-71ba-8e9d-525a1aff6954",
          mimeType: "image/jpeg",
          width: 1481,
          height: 1024,
        },
        {
          firecrawlImageUrl:
            "https://www.happyboards.com/_next/image?url=https%3A%2F%2Fhappyoms-production.s3.us-east-2.amazonaws.com%2Fmenu-media%2Fitems%2Fcml5g7q8w000t0dpi32vxpkgm%2Fimages%2F1779212117696-3-4_person_breakfast_box.jpg%3FX-Amz-Algorithm%3DAWS4-HMAC-SHA256%26X-Amz-Content-Sha256%3DUNSIGNED-PAYLOAD%26X-Amz-Credential%3DAKIAUOMPNW3C6QZBNHSI%252F20260609%252Fus-east-2%252Fs3%252Faws4_request%26X-Amz-Date%3D20260609T164455Z%26X-Amz-Expires%3D3600%26X-Amz-Signature%3D579945a8e84f5b2c4e75dac3933722842e99249086dca7b7930ab720e486869b%26X-Amz-SignedHeaders%3Dhost%26x-amz-checksum-mode%3DENABLED%26x-id%3DGetObject&w=3840&q=75",
          firecrawlAltText: null,
          firecrawlRole: null,
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019ead46-7142-7674-88af-da2168fbb1d6",
          mimeType: "image/jpeg",
          width: 1024,
          height: 1365,
        },
      ],
    },
  },
  {
    id: "cape-coast-co",
    label: "Cape Coast Co.",
    websiteUrl: "https://capecoast.co",
    brandStyle: {
      name: "Cape Coast Co.",
      brandName: "Cape Coast Co.",
      website: "capecoast.co",
      colorScheme: "light",
      backgroundColor: "#F7F4ED",
      foregroundColor: "#0F171F",
      accentColor: "#0F171F",
      headingFontFamily: "Playfair Display",
      bodyFontFamily: "Inter",
      buttonBackgroundColor: "#52616F",
      buttonTextColor: "#FFFFFF",
      buttonBorderColor: null,
      buttonBorderRadiusPx: 0,
      brandSubtext:
        "Ready-to-drink coffee and freshly roasted whole bean, made with the same standard.",
      footerAddress: null,
      logoCdnUrl:
        "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019eace4-ba02-7022-b258-c504835f0021",
      logoWidth: 313,
      logoHeight: 320,
      firecrawlSourceUrl: "https://capecoast.co/",
      firecrawlPulledAt: "2026-06-09T14:58:54.506Z",
      firecrawlBrandName: "Cape Coast Co.",
      firecrawlHomepageSummary:
        "Cape Coast Co. offers high-quality, nitro-infused, ready-to-drink coffee and freshly roasted whole bean coffee sourced from a family legacy. Their products emphasize quality and simplicity in a variety of coffee formats.",
      firecrawlAudience:
        "Coffee enthusiasts looking for premium quality coffee products without preservatives or additives.",
      firecrawlToneWords: ["premium", "clean", "inviting", "trustworthy", "heritage"],
      firecrawlBusinessType: "Ecommerce",
      firecrawlBusinessModel: "Direct to Consumer",
      firecrawlPricingDetails: [
        "Decaf Nitro: From $16.00",
        "Cape Coast Blend Whole Bean: From $20.00",
        "Mocha Nitro Cold Brew: From $18.00",
        "Rio Azul Whole Bean: From $20.00",
        "Free shipping on orders over $50",
      ],
      firecrawlRecommendedEmailWorkflows: [
        "abandoned cart recovery",
        "trial activation",
        "replenishment reminder",
        "onboarding",
        "review request",
      ],
      firecrawlHeroHeadline: "Skip the line. Keep the standard.",
      firecrawlHeroSubheadline:
        "Flash-chilled nitro cans for when you’re moving. Freshly roasted whole bean for when you’re making coffee at home.",
      firecrawlPrimaryCtaText: "Shop Coffee",
      firecrawlSecondaryCtaText: "Subscribe & Save",
      firecrawlValueProps: [
        "Free shipping on orders over $50",
        "Premium quality coffee",
        "No sugar, no dairy, no preservatives",
        "Freshly roasted and nitro-infused coffee",
        "Simple and clean process",
      ],
      firecrawlWelcomeEmailCopy: {
        subject: "Welcome to Cape Coast Co.!",
        preheader: "Experience premium coffee like never before.",
        headline: "Enjoy the Best in Coffee, Delivered to You.",
        bodyParagraphs: [
          "Thank you for joining Cape Coast Co.! We’re excited to bring you the finest quality coffee, crafted with care and precision.",
          "Explore our range of nitro-infused ready-to-drink options and freshly roasted whole beans. With every sip, you’ll taste the dedication to quality that goes into our coffee. We look forward to being part of your coffee journey!",
        ],
      },
      firecrawlHeadingFontFamily: "Playfair Display",
      firecrawlHeadingFallbackFontFamily: "Georgia",
      firecrawlBodyFontFamily: "Inter",
      firecrawlBodyFallbackFontFamily: "Helvetica",
      firecrawlPrimaryColor: "#52616F",
      firecrawlSecondaryColor: "#BFB8B0",
      firecrawlAccentColor: "#0F171F",
      firecrawlBackgroundColor: "#F7F4ED",
      firecrawlTextColor: "#0F171F",
      firecrawlLinkColor: "#0F171F",
      firecrawlThemePreference: "light",
      firecrawlCtaBackgroundColor: "#52616F",
      firecrawlCtaTextColor: "#FFFFFF",
      firecrawlCtaBorderColor: "",
      firecrawlCtaBorderRadius: "0px",
      firecrawlScreenshotCdnUrl:
        "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/screenshot/019eace4-ba89-75ed-ad83-fd39f4d94efa",
      socialLinks: [
        {
          label: "Website",
          url: "https://capecoast.co/",
        },
        {
          label: "Instagram",
          url: "https://instagram.com/capecoastco",
        },
      ],
      firecrawlColors: [
        {
          firecrawlColor: "#52616F",
          firecrawlRole: "Primary",
          firecrawlComponent: "Brand palette",
          firecrawlUsage: "Main CTA, active state, or strongest brand mark.",
        },
        {
          firecrawlColor: "#BFB8B0",
          firecrawlRole: "Secondary",
          firecrawlComponent: "Brand palette",
          firecrawlUsage: "Supporting actions, surfaces, or contrast color.",
        },
        {
          firecrawlColor: "#0F171F",
          firecrawlRole: "Accent",
          firecrawlComponent: "Brand palette",
          firecrawlUsage: "Small highlight, badge, or emphasis color.",
        },
        {
          firecrawlColor: "#F7F4ED",
          firecrawlRole: "Background",
          firecrawlComponent: "Page background",
          firecrawlUsage: "Dominant page or content surface.",
        },
        {
          firecrawlColor: "#0F171F",
          firecrawlRole: "Text",
          firecrawlComponent: "Text",
          firecrawlUsage: "Default body text on the main surface.",
        },
        {
          firecrawlColor: "#0F171F",
          firecrawlRole: "Link",
          firecrawlComponent: "Links",
          firecrawlUsage: "Standalone text links, not button labels.",
        },
        {
          firecrawlColor: "#FFFFFF",
          firecrawlRole: "Background",
          firecrawlComponent: "page",
          firecrawlUsage: "Main background color.",
        },
        {
          firecrawlColor: "#D6D6D6",
          firecrawlRole: "Background",
          firecrawlComponent: "cards",
          firecrawlUsage: "Card background color.",
        },
      ],
      firecrawlImages: [
        {
          firecrawlImageUrl:
            "https://pub-bb2e103a32db4e198524a2e9ed8f35b4.r2.dev/c1c4a445-bf3d-4d2b-9e4e-1691e65c6dc5/id-preview-de3655d2--65589a14-c587-4910-bb05-462de72e788d.lovable.app-1774380000758.png",
          firecrawlAltText: null,
          firecrawlRole: "OG Image",
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019eace4-bd48-70e2-a25b-9f153fa1a5d7",
          mimeType: "image/png",
          width: 1920,
          height: 4727,
        },
        {
          firecrawlImageUrl: "https://capecoast.co/assets/logo-option-2-DiH2CzMZ.png",
          firecrawlAltText: "Cape Coast Co. logo",
          firecrawlRole: "logo",
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019eace4-ba02-7022-b258-c504835f0021",
          mimeType: "image/png",
          width: 313,
          height: 320,
        },
        {
          firecrawlImageUrl:
            "https://cdn.shopify.com/s/files/1/0813/4387/3339/files/Untitled_design_39089f7f-b418-4ad5-93b1-13a5bb1a71ae.png?v=1777331406&width=1920",
          firecrawlAltText: "Cape Coast Co. ready-to-drink coffee",
          firecrawlRole: "hero image",
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019eace4-c3a6-73cb-8a36-cf06859f6153",
          mimeType: "image/png",
          width: 1920,
          height: 1281,
        },
        {
          firecrawlImageUrl:
            "https://cdn.shopify.com/s/files/1/0813/4387/3339/files/2_b3a2018b-d8bd-4e0f-af2c-e77dcdb99fda.png?v=1778798978",
          firecrawlAltText: null,
          firecrawlRole: null,
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019eace4-beca-773d-8509-41896a494782",
          mimeType: "image/png",
          width: 2048,
          height: 2048,
        },
        {
          firecrawlImageUrl:
            "https://cdn.shopify.com/s/files/1/0813/4387/3339/files/Untitled_design_4.png?v=1712856146",
          firecrawlAltText: null,
          firecrawlRole: null,
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019eace4-bf4d-70a7-bd8a-5f0956277eec",
          mimeType: "image/png",
          width: 1920,
          height: 1080,
        },
        {
          firecrawlImageUrl:
            "https://cdn.shopify.com/s/files/1/0813/4387/3339/files/1_8cf27fbd-9240-433e-8176-eac7de8b773f.png?v=1778798832",
          firecrawlAltText: null,
          firecrawlRole: null,
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019eace4-bc7c-724f-a75e-4c0de6bd21e4",
          mimeType: "image/png",
          width: 2048,
          height: 2048,
        },
      ],
    },
  },
  {
    id: "netlify",
    label: "Netlify",
    websiteUrl: "https://netlify.com",
    brandStyle: {
      name: "Netlify",
      brandName: "Netlify",
      website: "netlify.com",
      colorScheme: "light",
      backgroundColor: "#FFFFFF",
      foregroundColor: "#181A1C",
      accentColor: "#32E6E2",
      headingFontFamily: "Inter",
      bodyFontFamily: "Arial",
      buttonBackgroundColor: "#32E6E2",
      buttonTextColor: "#12181F",
      buttonBorderColor: "#32E6E2",
      buttonBorderRadiusPx: 360,
      brandSubtext: "Push your ideas to the web.",
      footerAddress: null,
      logoCdnUrl:
        "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/logo/019e9820-fc5a-756a-a9b9-a353bb730c6b",
      logoWidth: 1365,
      logoHeight: 557,
      firecrawlSourceUrl: "https://netlify.com/",
      firecrawlPulledAt: "2026-06-05T14:12:40.109Z",
      firecrawlBrandName: "Netlify",
      firecrawlHomepageSummary:
        "Netlify is a platform that enables users to build and deploy modern web applications quickly and efficiently, leveraging AI tools, Git integration, and a global infrastructure.",
      firecrawlAudience:
        "Developers and businesses looking for efficient web development and deployment solutions.",
      firecrawlToneWords: ["Innovative", "Efficient", "Supportive", "User-Friendly", "Reliable"],
      firecrawlBusinessType: "SaaS",
      firecrawlBusinessModel: "Subscription-based with various service offerings.",
      firecrawlPricingDetails: ["No public pricing found."],
      firecrawlRecommendedEmailWorkflows: [
        "Onboarding",
        "Trial Activation",
        "Abandoned Cart Recovery",
        "Usage Milestone",
        "Renewal Reminder",
      ],
      firecrawlHeroHeadline: "Build and Ship with AI",
      firecrawlHeroSubheadline:
        "Your app, live instantly. From AI tools or Git to global deployment in seconds.",
      firecrawlPrimaryCtaText: "Start Building",
      firecrawlSecondaryCtaText: "Talk to Sales",
      firecrawlValueProps: [
        "Instant global deployment",
        "AI and Git integration",
        "Robust infrastructure with 99.99% uptime",
        "Comprehensive customer support",
        "Versatile use cases from marketing to ecommerce",
      ],
      firecrawlWelcomeEmailCopy: {
        subject: "Welcome to Netlify!",
        preheader: "Let's get started on your web journey.",
        headline: "Your journey to effortless deployment starts here.",
        bodyParagraphs: [
          "Thank you for choosing Netlify! We’re excited to be a part of your development journey. Our platform is designed to help you deploy and manage your web projects effortlessly.",
          "Whether you’re building prototypes, launching apps, or optimizing existing projects, you have the tools you need at your fingertips.",
          "Dive right in, explore the capabilities of our platform, and see how we can help you bring your ideas to life.",
        ],
      },
      firecrawlHeadingFontFamily: "Inter",
      firecrawlHeadingFallbackFontFamily: "Helvetica",
      firecrawlBodyFontFamily: "Arial",
      firecrawlBodyFallbackFontFamily: "",
      firecrawlPrimaryColor: "#32E6E2",
      firecrawlSecondaryColor: "#9DA7B2",
      firecrawlAccentColor: "#32E6E2",
      firecrawlBackgroundColor: "#FFFFFF",
      firecrawlTextColor: "#181A1C",
      firecrawlLinkColor: "#2E51ED",
      firecrawlThemePreference: "light",
      firecrawlCtaBackgroundColor: "#32E6E2",
      firecrawlCtaTextColor: "#12181F",
      firecrawlCtaBorderColor: "#32E6E2",
      firecrawlCtaBorderRadius: "360px",
      firecrawlScreenshotCdnUrl:
        "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/screenshot/019e9820-fe1e-768c-8a4b-c9cc60738071",
      socialLinks: [
        {
          label: "Website",
          url: "https://netlify.com/",
        },
        {
          label: "GitHub",
          url: "https://github.com/netlify",
        },
        {
          label: "LinkedIn",
          url: "https://www.linkedin.com/company/netlify",
        },
        {
          label: "X",
          url: "https://twitter.com/netlify",
        },
        {
          label: "YouTube",
          url: "https://www.youtube.com/@NetlifyApp",
        },
      ],
      firecrawlColors: [
        {
          firecrawlColor: "#32E6E2",
          firecrawlRole: "Primary",
          firecrawlComponent: "Brand palette",
          firecrawlUsage: "Main CTA, active state, or strongest brand mark.",
        },
        {
          firecrawlColor: "#9DA7B2",
          firecrawlRole: "Secondary",
          firecrawlComponent: "Brand palette",
          firecrawlUsage: "Supporting actions, surfaces, or contrast color.",
        },
        {
          firecrawlColor: "#32E6E2",
          firecrawlRole: "Accent",
          firecrawlComponent: "Brand palette",
          firecrawlUsage: "Small highlight, badge, or emphasis color.",
        },
        {
          firecrawlColor: "#FFFFFF",
          firecrawlRole: "Background",
          firecrawlComponent: "Page background",
          firecrawlUsage: "Dominant page or content surface.",
        },
        {
          firecrawlColor: "#181A1C",
          firecrawlRole: "Text",
          firecrawlComponent: "Text",
          firecrawlUsage: "Default body text on the main surface.",
        },
        {
          firecrawlColor: "#2E51ED",
          firecrawlRole: "Link",
          firecrawlComponent: "Links",
          firecrawlUsage: "Standalone text links, not button labels.",
        },
        {
          firecrawlColor: "#00C4B4",
          firecrawlRole: "Primary",
          firecrawlComponent: "Buttons",
          firecrawlUsage: "Button fills",
        },
        {
          firecrawlColor: "#F6F8F9",
          firecrawlRole: "Background",
          firecrawlComponent: "Sections",
          firecrawlUsage: "Subtle backgrounds",
        },
      ],
      firecrawlImages: [
        {
          firecrawlImageUrl: "https://www.netlify.com/favicon/favicon.ico",
          firecrawlAltText: null,
          firecrawlRole: "Favicon",
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019e9820-fcd9-75a9-81e7-e125475d6983",
          mimeType: "image/vnd.microsoft.icon",
          width: 48,
          height: 48,
        },
        {
          firecrawlImageUrl: "https://www.netlify.com/images/og-image-default.png",
          firecrawlAltText: null,
          firecrawlRole: "OG Image",
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019e9820-fcd6-75ad-b8f5-a119d4385087",
          mimeType: "image/png",
          width: 1200,
          height: 630,
        },
        {
          firecrawlImageUrl: "https://www.netlify.com/images/home/switchback-1.svg",
          firecrawlAltText: "Illustration showing a code editor and related icons",
          firecrawlRole: "Illustration",
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019e9820-fe02-7444-816f-e083ea64e54c",
          mimeType: "image/png",
          width: 1269,
          height: 1051,
        },
        {
          firecrawlImageUrl: "https://www.netlify.com/images/home/switchback-2.svg",
          firecrawlAltText: "Illustration showing a browser window with connected elements",
          firecrawlRole: "Illustration",
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019e9820-fe55-734d-856a-cc8e4ce20894",
          mimeType: "image/png",
          width: 1469,
          height: 885,
        },
        {
          firecrawlImageUrl: "https://www.netlify.com/images/home/switchback-3.svg",
          firecrawlAltText: "Illustration representing rollback and increasing metrics",
          firecrawlRole: "Illustration",
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019e9820-fe4f-7158-8065-25b3079747dd",
          mimeType: "image/png",
          width: 1171,
          height: 971,
        },
        {
          firecrawlImageUrl: "https://www.netlify.com/images/home/logos/figma.svg",
          firecrawlAltText: null,
          firecrawlRole: null,
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019e9820-fdff-71cc-82bf-6571ce3c5b8b",
          mimeType: "image/png",
          width: 248,
          height: 93,
        },
      ],
    },
  },
  {
    id: "abstraction-capital",
    label: "Abstraction",
    websiteUrl: "https://abstraction.vc",
    brandStyle: {
      name: "Abstraction Capital",
      brandName: "Abstraction Capital",
      website: "abstraction.vc",
      colorScheme: "light",
      backgroundColor: "#FFFFFF",
      foregroundColor: "#000000",
      accentColor: "#F95252",
      headingFontFamily: "JetBrains Mono",
      bodyFontFamily: "JetBrains Mono",
      buttonBackgroundColor: "#FFFFFF",
      buttonTextColor: "#000000",
      buttonBorderColor: "#808080",
      buttonBorderRadiusPx: 10,
      brandSubtext: "Early stage capital for technical founders building technical tools",
      footerAddress: null,
      logoCdnUrl:
        "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019eacf6-d24d-74f9-bd3b-5eccfd2356ec",
      logoWidth: 256,
      logoHeight: 256,
      firecrawlSourceUrl: "https://abstraction.vc/",
      firecrawlPulledAt: "2026-06-09T15:18:37.962Z",
      firecrawlBrandName: "Abstraction Capital",
      firecrawlHomepageSummary:
        "Abstraction Capital focuses on investing in early-stage companies, specifically in the technical domain, to enable developers to concentrate on high-value projects.",
      firecrawlAudience:
        "Technical founders and startup developers seeking funding for innovative software solutions.",
      firecrawlToneWords: ["innovative", "supportive", "insightful", "engaging", "technical"],
      firecrawlBusinessType: "Venture Capital",
      firecrawlBusinessModel: "Investments in early-stage companies",
      firecrawlPricingDetails: ["No public pricing found."],
      firecrawlRecommendedEmailWorkflows: [
        "onboarding",
        "winback",
        "trial activation",
        "product recommendation",
        "renewal",
      ],
      firecrawlHeroHeadline: "We invest in glue",
      firecrawlHeroSubheadline: "The glue that connects technical founders with their dreams.",
      firecrawlPrimaryCtaText: "Let's Discuss",
      firecrawlSecondaryCtaText: "View Our Portfolio",
      firecrawlValueProps: [
        "Investing in early-stage tech startups",
        "Supporting developers with capital and resources",
        "Fostering innovation in software development",
        "Bridging the gap between funding and technical solutions",
        "Expertise in developer experience and software infrastructure",
      ],
      firecrawlWelcomeEmailCopy: {
        subject: "Welcome to Abstraction Capital!",
        preheader: "We're excited to have you on board.",
        headline: "Kickstart Your Journey with Us!",
        bodyParagraphs: [
          "Welcome to Abstraction Capital! We're thrilled that you've chosen to partner with us as we invest in transformative technologies and exceptional founders.",
          "At Abstraction, we believe in empowering technical teams to focus on what they do best—building innovative solutions. Our team is dedicated to providing the resources and guidance you need for your startup's success.",
          "Stay tuned for insights, resources, and updates from our portfolio companies. We're excited to support you on your journey!",
        ],
      },
      firecrawlHeadingFontFamily: "JetBrains Mono",
      firecrawlHeadingFallbackFontFamily: "Helvetica",
      firecrawlBodyFontFamily: "JetBrains Mono",
      firecrawlBodyFallbackFontFamily: "Courier New",
      firecrawlPrimaryColor: "#0D6EFD",
      firecrawlSecondaryColor: "#6C757D",
      firecrawlAccentColor: "#F95252",
      firecrawlBackgroundColor: "#FFFFFF",
      firecrawlTextColor: "#000000",
      firecrawlLinkColor: "#1F2E41",
      firecrawlThemePreference: "light",
      firecrawlCtaBackgroundColor: "#FFFFFF",
      firecrawlCtaTextColor: "#000000",
      firecrawlCtaBorderColor: "#808080",
      firecrawlCtaBorderRadius: "10px",
      firecrawlScreenshotCdnUrl:
        "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/screenshot/019eacf6-d2e2-756a-beb7-9101ebe275cd",
      socialLinks: [
        {
          label: "Website",
          url: "https://abstraction.vc/",
        },
        {
          label: "X",
          url: "https://twitter.com/taylor_w_c",
        },
        {
          label: "LinkedIn",
          url: "https://www.linkedin.com/company/abstraction-capital/",
        },
      ],
      firecrawlColors: [
        {
          firecrawlColor: "#0D6EFD",
          firecrawlRole: "Primary",
          firecrawlComponent: "Brand palette",
          firecrawlUsage: "Main CTA, active state, or strongest brand mark.",
        },
        {
          firecrawlColor: "#6C757D",
          firecrawlRole: "Secondary",
          firecrawlComponent: "Brand palette",
          firecrawlUsage: "Supporting actions, surfaces, or contrast color.",
        },
        {
          firecrawlColor: "#F95252",
          firecrawlRole: "Accent",
          firecrawlComponent: "Brand palette",
          firecrawlUsage: "Small highlight, badge, or emphasis color.",
        },
        {
          firecrawlColor: "#FFFFFF",
          firecrawlRole: "Background",
          firecrawlComponent: "Page background",
          firecrawlUsage: "Dominant page or content surface.",
        },
        {
          firecrawlColor: "#000000",
          firecrawlRole: "Text",
          firecrawlComponent: "Text",
          firecrawlUsage: "Default body text on the main surface.",
        },
        {
          firecrawlColor: "#1F2E41",
          firecrawlRole: "Link",
          firecrawlComponent: "Links",
          firecrawlUsage: "Standalone text links, not button labels.",
        },
        {
          firecrawlColor: "#FFFFFF",
          firecrawlRole: "Background",
          firecrawlComponent: "page",
          firecrawlUsage: "Main page background",
        },
        {
          firecrawlColor: "#F9FAFB",
          firecrawlRole: "Section Background",
          firecrawlComponent: "sections",
          firecrawlUsage: "Background for highlighted sections",
        },
      ],
      firecrawlImages: [
        {
          firecrawlImageUrl: "https://abstraction.vc/favicon.ico?v=2",
          firecrawlAltText: null,
          firecrawlRole: "Favicon",
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019eacf6-d24d-74f9-bd3b-5eccfd2356ec",
          mimeType: "image/vnd.microsoft.icon",
          width: 256,
          height: 256,
        },
        {
          firecrawlImageUrl: "https://abstraction.vc/images/AC-Logo-II.svg",
          firecrawlAltText: "Abstraction Capital Logo",
          firecrawlRole: "logo",
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019eacf6-d22c-70ac-988a-d4a189b94fe7",
          mimeType: "image/png",
          width: 1731,
          height: 272,
        },
        {
          firecrawlImageUrl: "https://abstraction.vc/images/illustrations/Header.svg",
          firecrawlAltText: "Illustration related to investment and technology",
          firecrawlRole: "header image",
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019eacf6-d260-715f-87bf-001f3fa022f1",
          mimeType: "image/png",
          width: 2235,
          height: 1397,
        },
        {
          firecrawlImageUrl: "https://abstraction.vc/images/taylor2.jpg",
          firecrawlAltText: "Picture of Taylor Clauson",
          firecrawlRole: "founder image",
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019eacf6-d2df-752d-a840-11640d0ae498",
          mimeType: "image/jpeg",
          width: 1199,
          height: 1798,
        },
        {
          firecrawlImageUrl: "https://abstraction.vc/images/logos/Wilderness-Labs-Logo-Azure.png",
          firecrawlAltText: null,
          firecrawlRole: null,
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019eacf6-d1f5-72ca-9d9e-bef59e746c91",
          mimeType: "image/png",
          width: 1345,
          height: 804,
        },
        {
          firecrawlImageUrl: "https://abstraction.vc/images/logos/octane.png",
          firecrawlAltText: null,
          firecrawlRole: null,
          cdnUrl:
            "https://pub-b7d1d21b38d243a598e39ed0924bf4ae.r2.dev/11111111-1111-4111-8111-111111111111/brand-styles/image/019eacf6-d08a-738e-91bf-4a45d2723b07",
          mimeType: "image/png",
          width: 212,
          height: 226,
        },
      ],
    },
  },
];
