import type { JobRecord } from "./types.js";

export const SUPABASE_EDGE_FUNCTIONS_DEPLOY_SCRIPT_FILENAME =
  "deploy-edge-functions-to-target.sh" as const;

const trimOrNull = (value: string | null | undefined): string | null => {
  if (!value) return null;
  const t = value.trim();
  return t.length > 0 ? t : null;
};

/** Hostname must be `<project_ref>.supabase.co` (project ref is lowercase alphanumerics). */
export const parseSupabaseProjectRefFromProjectUrl = (projectUrl: string): string | null => {
  try {
    const u = new URL(projectUrl.trim());
    if (!["http:", "https:"].includes(u.protocol)) return null;
    const host = u.hostname.toLowerCase();
    const match = /^([a-z0-9][a-z0-9-]*)\.supabase\.co$/.exec(host);
    return match?.[1] ?? null;
  } catch {
    return null;
  }
};

/** Map `db.<ref>.supabase.co` to `https://<ref>.supabase.co`. */
export const tryInferSupabaseProjectUrlFromDbHost = (
  host: string | null | undefined,
): string | null => {
  if (!host) return null;
  const match = /^db\.([a-z0-9][a-z0-9-]*)\.supabase\.co$/i.exec(host.trim().toLowerCase());
  return match ? `https://${match[1]}.supabase.co` : null;
};

const normalizeHttpsProjectUrl = (url: string): string => {
  const u = new URL(url.trim());
  return `${u.protocol}//${u.host}`;
};

export type DeployScriptTarget = {
  targetProjectUrl: string;
  targetProjectRef: string;
};

export const resolveDeployTargetFromJob = (job: JobRecord): DeployScriptTarget | null => {
  const debug = job.debug;
  if (!debug) return null;

  const explicit = trimOrNull(debug.target_project_url);
  if (explicit) {
    const ref = parseSupabaseProjectRefFromProjectUrl(explicit);
    if (!ref) return null;
    return {
      targetProjectUrl: normalizeHttpsProjectUrl(explicit),
      targetProjectRef: ref,
    };
  }

  const inferredUrl = tryInferSupabaseProjectUrlFromDbHost(debug.target?.host ?? null);
  if (!inferredUrl) return null;
  const ref = parseSupabaseProjectRefFromProjectUrl(inferredUrl);
  if (!ref) return null;
  return { targetProjectUrl: inferredUrl, targetProjectRef: ref };
};

export const renderSupabaseEdgeFunctionsDeployScript = (params: {
  targetProjectUrl: string;
  targetProjectRef: string;
}): string => {
  const url = params.targetProjectUrl.replace(/'/g, "'\"'\"'");
  const ref = params.targetProjectRef.replace(/'/g, "'\"'\"'");
  return `#!/usr/bin/env bash
set -euo pipefail

# Generated by lovable-cloud-to-supabase-exporter — deploy Edge Functions to your Supabase project.
# Requires Supabase CLI: https://supabase.com/docs/guides/cli
# Usage: ./${SUPABASE_EDGE_FUNCTIONS_DEPLOY_SCRIPT_FILENAME} [path-to-directory-containing-supabase]
#
# If the optional path is omitted, this script expects a ./supabase directory in the current directory.
# The path may be the project root (directory that contains supabase/) or the supabase/ directory itself.

TARGET_PROJECT_URL='${url}'
TARGET_PROJECT_REF='${ref}'

resolve_supabase_project_root() {
  local arg="\${1-}"
  if [[ -n "$arg" ]]; then
    if [[ -d "$arg/supabase" ]]; then
      (cd "$arg" && pwd)
      return
    fi
    if [[ "$(basename "$arg")" == "supabase" ]] && [[ -d "$arg" ]]; then
      (cd "$arg/.." && pwd)
      return
    fi
    echo "error: expected a directory containing supabase/, or the supabase/ directory itself: $arg" >&2
    exit 1
  fi
  if [[ -d "./supabase" ]]; then
    pwd
    return
  fi
  echo "error: no ./supabase directory in the current working directory. Pass the project root or path to supabase/." >&2
  exit 1
}

ROOT="$(resolve_supabase_project_root "$@")"
cd "$ROOT"

if ! command -v supabase >/dev/null 2>&1; then
  echo "error: supabase CLI not found. Install: https://supabase.com/docs/guides/cli" >&2
  exit 1
fi

echo "Logging in to Supabase (browser)..."
supabase login

echo "Linking to project $TARGET_PROJECT_REF ($TARGET_PROJECT_URL)..."
supabase link --project-ref "$TARGET_PROJECT_REF"

echo "Deploying Edge Functions..."
supabase functions deploy
`;
};
